spring.application.name=TripFlow
server.port=8989

spring.datasource.url=jdbc:postgresql://localhost:5432/TripFlow
spring.datasource.username=tripflow
spring.datasource.password=minimanimo28!@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true